### ISSUE TITLE
List of intents that the demo supports?

### ISSUE THREAD

**Issue by minghia** [Picovoice/rhino#10]
What is the list of intents that the demo files support? 

I tried to recreate the working audio file using audacity but the only I way I could the demo to match my voice was to include the silence at the beginning and the end of the wav file. Is this expected behaviour?

Tony V

**Comment by kenarsa** [comment]
There are a few free contexts available under resources/ 

Elaborate on the late issue please ...

**Comment by minghia** [comment]
So for the various contexts under free what are the words that three present understand? As far as I can tell the only thing that the coffee maker parsers is what is in the sample audio file. Are there any other phrase it can understand.

With regards to the audio parsing problem, I initially tried to record the example phrase as just reading it and the demo program couldn't parse the intent from the wav file. When I  used audacity to make it match the timing of your recorded file by placing a silence at the start and at the end of the recorded it audio it gives me the same intent. 

Hope this helps.

**Comment by kenarsa** [comment]
for each context, you can print out the expressions, slots, and values using pv_rhino_expressions() https://github.com/Picovoice/rhino/blob/master/include/pv_rhino.h#L118-L126

There is no need for silence at the start. silence at the end is needed for endpointing (i.e. detecting when the user is done).
