### ISSUE TITLE
Rhino using French on Flutter

### ISSUE THREAD

**Issue by wawaBen** [Picovoice/rhino#101]
Dear Picovoice team,

I am trying to run picovoice on French but I get trouble to load a french custom model (created using the console).
I get error loading model without further info. Should I add french context somewhere ? 
I only added the .rhn model in my asset  

`pico_voice % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.2.3 20D91 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

• No issues found!`

`
n Observatory debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:54807/P1AkUQBJ8Oc=/
flutter: Failed to initialize Rhino: Failed to initialize Rhino.
The Flutter DevTools debugger and profiler on iPhone 12 Pro Max is available at:
http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A54807%2FP1AkUQBJ8Oc%3D%2F
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: LateInitializationError: Field '_rhinoManager@606092562' has not been initialized.

`

**Comment by kenarsa** [comment]
are you loading the [French model](https://github.com/Picovoice/rhino/blob/master/lib/common/rhino_params_fr.pv)?

**Comment by wawaBen** [comment]
Hi, yes 

`Future<void> initRhino() async {
    String contextPath = await _extractDemoContext();

    try {
      _rhinoManager = await RhinoManager.create(contextPath, inferenceCallback,
          errorCallback: errorCallback,
          modelPath: 'assets/contexts/rhino_params_fr.pv');
    } on PvError catch (ex) {
      print("Failed to initialize Rhino: ${ex.message}");
    } finally {
      this.setState(() {
        isButtonDisabled = false;
      });
    }
  }`

**Comment by wawaBen** [comment]
Hello guys, 
Even if I try to load english context using modelPath in the create function I get the error : 
`flutter: Failed to initialize Rhino: Failed to initialize Rhino.`

I tried relative / non relative path but unable to load it.

**Comment by laves** [comment]
@wawaBen I see you're loading the French model with a path to the assets folder. Unfortunately, this doesn't work for binary file types in Flutter as they are compressed in the app bundle. Just like you do with the Rhino context, you have to read it from the app bundle and write it to another location before passing it into the create function.
