### ISSUE TITLE
Add Raspberry Pi support to Go binding

### ISSUE THREAD

**Issue by aehm2k5** [Picovoice/rhino#107]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
demo should compile

### Actual behaviour
doesnt compile
---- OUTPUT
$ go run micdemo/rhino_mic_demo.go 
# github.com/gen2brain/malgo
In file included from miniaudio.c:4:
miniaudio.h: In function ‘ma_device_data_loop_wakeup__alsa’:
miniaudio.h:20930:9: warning: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
20930 |         write(pDevice->alsa.wakeupfdCapture, &t, sizeof(t));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
miniaudio.h:20933:9: warning: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
20933 |         write(pDevice->alsa.wakeupfdPlayback, &t, sizeof(t));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
miniaudio.h: In function ‘ma_device_wait__alsa’:
miniaudio.h:20760:13: warning: ignoring return value of ‘read’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
20760 |             read(pPollDescriptors[0].fd, &t, sizeof(t));    /* <-- Important that we read here so that the next write() does not block. */
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# github.com/Picovoice/rhino/binding/go
/home/ubuntu/go/pkg/mod/github.com/!picovoice/rhino/binding/go@v1.6.0/rhino_posix.go:142:5: could not determine kind of name for C.bool
/home/ubuntu/go/pkg/mod/github.com/!picovoice/rhino/binding/go@v1.6.0/rhino_posix.go:148:12: could not determine kind of name for C.pv_rhino_is_understood_wrapper
/home/ubuntu/go/pkg/mod/github.com/!picovoice/rhino/binding/go@v1.6.0/rhino_posix.go:138:12: could not determine kind of name for C.pv_rhino_process_wrapper
cgo: 
gcc errors for preamble:
/home/ubuntu/go/pkg/mod/github.com/!picovoice/rhino/binding/go@v1.6.0/rhino_posix.go:34:67: error: unknown type name 'bool'
   34 | typedef int32_t (*pv_rhino_process_func)(void *, const int16_t *, bool *);
      |                                                                   ^~~~
/home/ubuntu/go/pkg/mod/github.com/!picovoice/rhino/binding/go@v1.6.0/rhino_posix.go:36:77: error: unknown type name 'bool'
   36 | int32_t pv_rhino_process_wrapper(void *f, void *object, const int16_t *pcm, bool *is_finalized) {
      |                                                                             ^~~~
/home/ubuntu/go/pkg/mod/github.com/!picovoice/rhino/binding/go@v1.6.0/rhino_posix.go:40:62: error: unknown type name 'bool'
   40 | typedef int32_t (*pv_rhino_is_understood_func)(const void *, bool *);
      |                                                              ^~~~
/home/ubuntu/go/pkg/mod/github.com/!picovoice/rhino/binding/go@v1.6.0/rhino_posix.go:42:69: error: unknown type name 'bool'
   42 | int32_t pv_rhino_is_understood_wrapper(void *f, const void *object, bool *is_understood) {
      |                                                                     ^~~~

### Steps to reproduce the behaviour
try to compile on a raspberry pi4

(Include enough details so that the issue can be reproduced independently.)

$ uname -a
Linux raspi4 5.8.0-1024-raspi #27-Ubuntu SMP PREEMPT Thu May 6 10:07:12 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy

$ go version
go version go1.16.4 linux/arm64

**Comment by aehm2k5** [comment]
if i add in rhino_posix.go
#include <stdbool.h>

it compiles but still get a error on running the app:

$ ./rhino_mic_demo -show_audio_devices
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x5441f3, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x54
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x29c

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4cdb80, 0x40000b1be8, 0x0)
        /usr/local/go/src/runtime/cgocall.go:154 +0x50 fp=0x40000b1bb0 sp=0x40000b1b70 pc=0x40e040
github.com/Picovoice/rhino/binding/go._Cfunc_pv_rhino_version_wrapper(0x0, 0x0)
        _cgo_gotypes.go:262 +0x44 fp=0x40000b1be0 sp=0x40000b1bb0 pc=0x4c1d64
github.com/Picovoice/rhino/binding/go.nativeRhinoType.nativeVersion.func1(0x0)
        /home/ubuntu/go/pkg/mod/github.com/!picovoice/rhino/binding/go@v1.6.0/rhino_posix.go:217 +0x50 fp=0x40000b1c20 sp=0x40000b1be0 pc=0x4c4630
github.com/Picovoice/rhino/binding/go.nativeRhinoType.nativeVersion(0x0, 0x0, 0x0, 0xa)
        /home/ubuntu/go/pkg/mod/github.com/!picovoice/rhino/binding/go@v1.6.0/rhino_posix.go:217 +0x20 fp=0x40000b1c50 sp=0x40000b1c20 pc=0x4c3580
github.com/Picovoice/rhino/binding/go.init()
        /home/ubuntu/go/pkg/mod/github.com/!picovoice/rhino/binding/go@v1.6.0/rhino.go:147 +0x2e4 fp=0x40000b1cb0 sp=0x40000b1c50 pc=0x4c4a14
runtime.doInit(0x86b000)
        /usr/local/go/src/runtime/proc.go:6309 +0xdc fp=0x40000b1e10 sp=0x40000b1cb0 pc=0x44b5bc
runtime.doInit(0x86b4c0)
        /usr/local/go/src/runtime/proc.go:6286 +0x60 fp=0x40000b1f70 sp=0x40000b1e10 pc=0x44b540
runtime.main()
        /usr/local/go/src/runtime/proc.go:208 +0x214 fp=0x40000b1fd0 sp=0x40000b1f70 pc=0x43d824
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1130 +0x4 fp=0x40000b1fd0 sp=0x40000b1fd0 pc=0x46ad24

**Comment by dbartle** [comment]
The Go bindings do not yet support Raspberry Pi devices (macOS, Linux, and Windows on x86_64 are supported). I will keep this issue open for visibility, and also the demo should output a coherent error message ideally if the platform is unsupported.

**Comment by Inviz** [comment]
Is arm generally unsupported?

**Comment by kenarsa** [comment]
This is now supported with the `v2.0` update!
