### ISSUE TITLE
Feature request: demo apps for 64bit ARM64/AARCH64

### ISSUE THREAD

**Issue by IOOOTARobby** [Picovoice/rhino#11]
Hi,
we are using a plain Ubuntu Xenial linux distro both on a RPi3+ board and another Cortex-A53 custom board and, in both cases, we use a 64bit version of the OS.
Is there any demo available that may run on our platforms?
The Python executable in our systems is a 64bit binary, hence it fails to load the shared libraries that you provide.
Thanks,

Roberto

**Comment by kenarsa** [comment]
Hello Roberto, we only provide support for custom boards within commercial engagements. Adding such support to open source repositories is not within our roadmap. If you like to make an inquiry feel free to reach out via this form: https://picovoice.ai/contact.html

**Comment by IOOOTARobby** [comment]
Hello Alireza,
I understand your point and we seriously take into account a commercial engagement, although Ubuntu Xenial on RPi3 is definitely _not_ custom, I dare to say it is a very common use-case: the question was more about delivering true 64bit libraries for ARM in general, not related to our custom boards.
Without that it is even difficult for us to just make a real world test.

Thanks a lot.
