### ISSUE TITLE
Rhino Issue:  

### ISSUE THREAD

**Issue by edahn777** [Picovoice/rhino#116]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
I expect to build iOS project with the custom Rhino context file.  

### Actual behaviour
Project cannot find my custom Rhino file and the Teminal states that  it cannot find the model file. 
error messages are shown as below:

- porcupineError(Porcupine.PorcupineError.invalidArgument(message: "Model file at does not exist at \'\' "))

### Steps to reproduce the behaviour
Please guide me how to solve this issue.

(Include enough details so that the issue can be reproduced independently.)

**Comment by dbartle** [comment]
This is your third time filing this issue and you are still not providing the minimum information. I'm going to block you from Picovoice repositories for 30 days because this is not respectful of our time.
