### ISSUE TITLE
Possible to have a generic slot?

### ISSUE THREAD

**Issue by AlexHartford** [Picovoice/rhino#124]
Hi, I'm very interested in using this package for a Flutter app I'm working on.

I'm wondering if it is possible to have a slot that works somewhat like a wildcard. For example, a "food" slot is naturally difficult to make as listing all foods in a slot isn't really feasible.

I tried to use the built-in $pv.Alphabetic slot but that seems to pick up individual letters instead of whole words.

Some examples to demonstrate exactly what I'd like to do:

`How many calories are in $pv.TwoDigitInteger:quantity servings of $food:food?`
`What pairs well with $food:food_a and $food:food_b?`

**Comment by saintpepsicola** [comment]
I am looking for the same thing!

I want to be able to have some wildcard variables to store three digit numbers etc

**Comment by dbartle** [comment]
Great question! The short answer is no; here's why:

A wildcard, as described, would need to understand every possible word or phrase in English (or whichever language). This means generic speech transcription (STT), which has significantly greater processing requirements than the approach used by Rhino. With Rhino, you have a bespoke model that understands your particular combinations of words or phrases and that (plus extreme optimization and proprietary deep learning technology) is why it excels at accuracy and efficiency.

Now, for your specific example of foods, if you are wanting to do something meaningful with those food slots, then I would assume that you're going to look them up in a database. I don't see anything infeasible about putting the contents of such a database into a Rhino context. It might take a little effort, but I don't see any reason that particular use case could not be accommodated.

**Comment by AlexHartford** [comment]
Thanks for the quick reply!

Yes, you're correct - however, I am using a 3rd party API for getting food data.

I don't know if I'm understanding your suggestion fully, are you suggesting adding every entry of a database into a food slot? I also considered this after I posted this issue, and it could probably be done.

So fuzzy matching is not really in the cards for rhino then. Like @saintpepsicola said, being able to recognize multidigit numbers would also be something I would likely need.  I admittedly don't fully understand the guts of how speech recognition works, but being able to fuzzy match multicharacter alphabetics/alphanumerics would greatly increase the scope of problems rhino solves. If rhino isn't going in this direction, is there any chance this is implemented in another SDK in the future?

**Comment by dbartle** [comment]
> I don't know if I'm understanding your suggestion fully, are you suggesting adding every entry of a database into a food slot? I also considered this after I posted this issue, and it could probably be done.

Yes. You can import and export in CSV format. We had a previous intern who used this approach to import thousands of descriptions of Emoji into a context. It required a little clean up effort to map some things like "8ball" to "eight ball" but overall worked quite well.

> being able to recognize multidigit numbers would also be something I would likely need.

There's a sharp difference between things like alphanumerics, dates, multi-digit numbers and more broad/fuzzy notions like food or people's names. 

Multi-digit numbers, dates, things like that are achievable and if you specifically want _that_, I suggest opening a feature request issue and we can gauge if it merits implementation on our end based on the traction of the issue. We currently also have one open for dates: https://github.com/Picovoice/rhino/issues/70.

> If rhino isn't going in this direction, is there any chance this is implemented in another SDK in the future?

Can't tell you anything specifically on the roadmap but both Rhino and our generalized STT products are under active development, so there will be more possibilities in the future.

**Comment by AlexHartford** [comment]
Thanks! I will give that a shot.
