### ISSUE TITLE
Rhino Issue: Undersores not supported in slot names

### ISSUE THREAD

**Issue by Inviz** [Picovoice/rhino#134]
As a way to overcome #133 i've built a yaml preprocessor that would enable optional slots, and add a syntax to define aliases for slot values. 

I noticed that slot names are very restrictive, they do not even allow underscores. 

### Expected behaviour
Allow underscores in slot names

### Actual behaviour
```"Slot command__close regex /^([A-Za-z]){1,32}$/"```

### Steps to reproduce the behaviour
Use underscore in slot name

Edit: Maybe this is not a bug, but I don't know how to change label now

**Comment by Inviz** [comment]
Could we also make it slots without name reference default to slot name? I.e. "Set color to $color" would be the same as "Set color to $color:color"

**Comment by dbartle** [comment]
These are both good and reasonable suggestions. I agree that from a newcomer perspective, the slot variable assignment syntax is confusing until you actually need it to disambiguate two slots. We will see if we can get this incorporated into the Rhino roadmap and subsequent release.

**Comment by ErisMik** [comment]
Thank you for the feedback. We've now updated the Rhino editor to allow for underscores (`_`) in `slot types`, `slot names` and `macro types`. We also now allow dashes (`-`), dots (`.`), numerics (`0 -> 9`) and a range of non-ascii accented characters (`é`, `ï`, `ü`, `ÿ`, etc).

I'm closing this issue for now. As usual, if you run into any more problems, feel free to open another issue.
