### ISSUE TITLE
permanently train Rhino inference models

### ISSUE THREAD

**Issue by sophyf** [Picovoice/rhino#137]
**Is your feature request related to a problem? Please describe.**
I am working on permanently installing a voice-controlled component for our research lab, and would like to avoid re-training and re-downloading the Rhino inference model file every 30 days.

**Describe the solution you'd like**
Is there a way to permanently train the Rhino inference model (so only need to download once?)

**Describe alternatives you've considered**
If we can't permanently train the Rhino file, I'm wondering if there is a way to integrate the porcupine wake word with the Picovoice Cheetah speech-to-text engine? (again to avoid re-downloading every month)

**Additional context**

**Comment by kenarsa** [comment]
@sophyf not at the moment. but this will change before the end of the year. closing for but I suggest subscribing to Picovoice's newsletter if you wanna stay in the loop.
