### ISSUE TITLE
Rhino Issue: Audio error when running on a background service

### ISSUE THREAD

**Issue by adhurimhajzeraj** [Picovoice/rhino#153]
Hi Picovoice,

I have been playing with Porcupine and Rhino on Android and recently came to a situation where the Rhino is showing an error when the app runs in the background (foreground service). It works well when the app is not in the background.
Any idea if I am doing something wrong, or is this a bug?

This is the message it shows:
E/IAudioFlinger: createRecord returned error -1
E/AudioRecord: createRecord_l(1225279496): AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.

**Comment by kenarsa** [comment]
@adhurimhajzeraj Unfortunately the information you provided does not allow us to reproduce your issue and hence we cannot help as much. In the future please make sure to enable us to reproduce. The error messages you provided does not provide nearly enough context. Nevertheless, I suggest you take a look at [Picovoice platform Android service demo](https://github.com/Picovoice/picovoice/tree/master/demo/android/Service). It uses both Porcupine and Rhino in a service. If that demo doesn't work for you please open an issue with enough information on that repo and we will help out.
