### ISSUE TITLE
non-English support for STM32 on GitHub

### ISSUE THREAD

**Issue by safsoun** [Picovoice/rhino#160]
I'm a newbie in Picovoice World and I don't know if this is the right place to ask a question because I dindn't find a forum for Picovoice.
Anyway, I created a Personal account to get started with Picovoice solution with a STM32 device (available demo) and it looks very cool.
My issue is that when I select the Langage French, I get this error:
[ERROR] context file belongs to 'fr' while model file belongs to 'en'
I already selected french langage in Rhino interface before generating the model! 
Does Personal account supports the usage of langages apart of English langage?
If yes, what is the issue? how can I test french langage with the current STM32 demo?
Thank you.

**Comment by kenarsa** [comment]
You are correct. We only provided English support for STM32 on GitHub and kept non-English support for enterprise customers. This is going to change in the next couple of months. We will keep this issue open and circle back when non-English language support for STM32 is on GitHub.

**Comment by kenarsa** [comment]
This is available now with the `v2.0` update!
