### ISSUE TITLE
Model used

### ISSUE THREAD

**Issue by anferico** [Picovoice/rhino#22]
What is the deep learning model used in the examples? I'm willing to run the C example on a [Sparkfun Edge](https://www.sparkfun.com/products/15170), which is powered by an [Ambiq Apollo3 Blue](https://www.ambiqmicro.com/mcu/) chip (featuring a Cortex M4 MCU), but I'm not sure it would work right away. 
However, I thought I could train the model myself and deploy it on my Sparkfun Edge if I knew the model's architecture and the dataset it was trained on. Actually, if you trained it using TensorFlow, a model checkpoint would be sufficient since the Sparkfun Edge is meant to run TensorFlow Lite models.

**Comment by kenarsa** [comment]
(1) The model used and information as such is proprietary information of Picovoice.
(2) Cortex-M support is only available for enterprise customers: https://github.com/Picovoice/rhino#rhino

Please read the docs before opening the issues.
