### ISSUE TITLE
[question] Can the context/model be trained on the end device?

### ISSUE THREAD

**Issue by tejas-n** [Picovoice/rhino#23]
Hi, we are thinking of trialling out Rhino on our custom android devices but can you tell us if it is possible to retrain the models on the devices so they are personalized for the end-users, please?
For example, if we wanted to design an intent which would let the user call the contacts on their device i.e. something like "Call [contact_on_device]", would it be possible to inject all the contact names on the user's device in the model so that it can recognize them?
Thank you.

**Comment by kenarsa** [comment]
It is possible. But not out of the box. If this is for a commercial application we might be able to help. If that's a case its best to reach out via form on picovoice website.

**Comment by tejas-n** [comment]
Okay, thanks for the reply.
