### ISSUE TITLE
Rhino Issue: issue when French language is used

### ISSUE THREAD

**Issue by safsoun** [Picovoice/rhino#240]
Hello,

I got a notification that different languages are now supported in rev 2.0.0 which is very nice (Issue #160). Thank you a lot for that.
However, I tried to a do a test with French language with STM32F769-Disco board, I got the following error:
[ERROR] Keyword files (.PPN) and model file (.PV) should belong to the same language. Keyword files belongs to 'fr' while model file belongs to 'en'.
This is what I did:
- In the console, and in Language menu I've selected French language.
- Created a new context.
- Fill the context with different commands in French.
- Save and train the model.
- Tested the command with the PC microphone in the console: the commands are detected perfectly.
- Downloaded the latest version of Picovoice from github and in the demo under \demo\mcu\stm32f769\stm32f769i-disco, copied the new generated context array in CONTEXT_ARRAY in pv_params.h in French section.
- Activated French language in the project preprocessor by replacing the flag __PV_LANGUAGE_ENGLISH__ by __PV_LANGUAGE_FRENCH__ then compiled the project.
- Loaded the project and at the beginning, in the trace, I got the previous error! 
Am I missing something?
Thank you for your help.

**Comment by mrrostam** [comment]
The project needs to be linked to an appropriate library based on the selected language as well. That's why there are 4 different configurations in the demo project. So just go ahead and select the French configuration from `Project` -> `Build configuration` -> `Set Active` -> `ReleaseFrench`. That should do the job.

**Comment by safsoun** [comment]
It's working now :) .. Thank you very much!
