### ISSUE TITLE
generic or wildcard slot revisited

### ISSUE THREAD

**Issue by rickmini** [Picovoice/rhino#244]
An earlier request for a generic slot was closed. But i have other questions:
Using Alexa, Google or Cortana, you can ask: "Play I dig a pony by the beatles" or "Give me Corona virus updates" The idea of using a database to daily update your Intents would be untenable.

What if you could could return the raw text along with the intent? 
[Give me] <placeholder> [updates]. 
Using the raw text it would be easy to determine the placeholder.

or alternatively use bookends slots:
(Please) [Give me] (the)  ?bookend?. generic text... ?bookend? [updates] 

If the bookends arent doable, why couldnt i get the raw text. It must be available?

**Comment by ksyeo1010** [comment]
Thanks for the request. Rhino is generally a Speech-to-Intent engine that works with audio. Therefore it can't really represent text. What you are asking for is a problem for speech to text and natural language understanding, basically extract text. You can read more about how it differs with Rhino [here](https://picovoice.ai/blog/end-to-end-intent-inference-from-speech/). If you have any more questions, feel free to re-open the issue or post a new one. For now I will be closing this issue as it isn't a feature that the Rhino engine can support.
