### ISSUE TITLE
Merging all languages in the same library

### ISSUE THREAD

**Issue by safsoun** [Picovoice/rhino#247]
Hello,

Is it possible to merge all languages in the same library so one can switch from a language to another in the same application at runtime?
Unfortunately, current implementation doesn't allow that.
Thank you.

**Comment by kenarsa** [comment]
What's the platform you are using and why is this desirable?

**Comment by safsoun** [comment]
For MCUs platforms' .. In multi langage applications for example English/Frensh in Canada or German/English in Germany .. 
It's a suggestion to enhance the library in order to make it more flexible 😊.
Thank you.

**Comment by kenarsa** [comment]
got it! appreciate the suggestion. if we do that then the size of the library nearly doubles and hence not a good choice due to limited flash on these devices. thanks again!
