### ISSUE TITLE
Circumvent Pronunciation Errors

### ISSUE THREAD

**Issue by DebVortex** [Picovoice/rhino#248]
### What is the URL of the doc?

https://picovoice.ai/docs/tips/syntax-cheat-sheet/ 

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

The documentation states, "Pronunciation checks are performed as you edit your context. Each word in the phrase must be present in the Picovoice dictionary." but it does not explain how to handle such problem.

### Whats the Problem?

Hello there,

I was happy to read the latest blogpost and decided to try it out by converting one of my rasa-NLU examples. I tried to make a way to simply query weather for a specific day and german town.

I have a List with ~1k german town names but a lot of them are not present in the dictionary (almost all of them). Any hints of how to circumvent this problem? It does not seem that I'm able to extend the dictionary by myself.

**Comment by kenarsa** [comment]
We don't have a mechanism right now to go around this. I am inclined to attack it and I think there are 2 possibilities: (1) auto-gen the pronunciations using our `g2p` (2) let the user enter pronunciation. this needs some thinking first and then needs to be implemented on Console. I keep this open to track but as of now, I cannot give a time estimate on when this would be done.

**Comment by DebVortex** [comment]
Hi @kenarsa ! `g2p` sounds jucy but the possiblity to enter it from the user sounds also great.

Take your time. Thanks for letting me know :-)

**Comment by kenarsa** [comment]
I don't think we can include this in our immediate roadmap in the coming months, unfortunately. I am closing this right now but will re-open if priorities change on our end.
