### ISSUE TITLE
Are built-in slot types available for non-English languages?

### ISSUE THREAD

**Issue by safsoun** [Picovoice/rhino#252]
Hello,

Are built-in slot types available for non-English languages?
I mean these ones :
pv.Alphabetic
pv.Alphanumeric
pv.Percent
pv.SingleDigitInteger
pv.SingleDigitOrdinal
pv.TwoDigitInteger
pv.TwoDigitOrdinal

I tested them in the console (French language) and it seems that they are not supported 😢 .
Thank you.

**Comment by safsoun** [comment]
Hello,

Thank you for the reply.. Hope it will be fixed asap 😉 ..

**Comment by ErisMik** [comment]
@safsoun We now have support for non-en builtin slots in [Console](https://console.picovoice.ai/).
