### ISSUE TITLE
Rhino Issue: 

### ISSUE THREAD

**Issue by NIHALNAVALE** [Picovoice/rhino#265]
In a created intent "move", the following expression is  not working: (please) [go to, enter, move to] room $pv.TwoDigitInteger:dst1

I even tried running a basic expression from cheatsheet: turn on lights in $room:r1 and $room:r2, here r1, r2 is not working even though I have a slot created. 

### Expected behaviour

{
  intent: "move",
  slots: {
    dst1: "1"
  }
}

### Actual behaviour

the variable dst1 is not working, but variable dst works.  
"Use alphabetic characters, apostrophes, and spaces for phrases. See the Expression Cheat Sheet for other allowed characters." is the error being shown.

### Steps to reproduce the behaviour

I am also not able to import the YAML file, the zip files are included below. 
[Navigation.zip](https://github.com/Picovoice/rhino/files/7766118/Navigation.zip)
[navigation_linux_v2.0.0.zip](https://github.com/Picovoice/rhino/files/7766119/navigation_linux_v2.0.0.zip)

This is a screenshot of the error.
![Screenshot from 2021-12-22 20-45-52](https://user-images.githubusercontent.com/37554484/147175209-ab587a22-7b5e-4918-a8f9-513a7bf1bfd0.png)

It used to work fine before, I've made a good intent detection model before, as shown below and faced no issues before.
![Screenshot from 2021-12-22 20-48-46](https://user-images.githubusercontent.com/37554484/147175292-d105b8ca-83bc-4913-becf-2fd16d87b5ef.png)

I am also not able to import the YAML file, this is the error being showed.
![Screenshot from 2021-12-22 20-53-57](https://user-images.githubusercontent.com/37554484/147175666-6ea0bc65-5327-4b02-ba8b-43d6a7e98bd6.png)

**Comment by kenarsa** [comment]
OK! Thanks for reporting this. Slots should be alphabetic. if you rename it to `dstOne` it should work. Now we plan to change this but the doc is misleading as is. I will keep this open to fix the doc.
