### ISSUE TITLE
Provide static libraries

### ISSUE THREAD

**Issue by hellow554** [Picovoice/rhino#301]
I'm trying to write an application with the rust SDK. Problem is, it needs the libpv_rhino in the build folder which is obviously not available on other platforms.
Static linking would circumvent this problem.

Are there any plans on providing such libraries, e.g. a `.a` file for unix OS and a `.lib` for windows?

The alternative is currently that I modify the wrapper, include the library inside of the binary, "unpack" it during runtime to a tempfile and use the libloading crate to load the unpacked library during runtime. Not a very good solution IMHO.

**Comment by hellow554** [comment]
Same goes for porcupine and pvrecorder

**Comment by ErisMik** [comment]
At this time there is no plan to provide static libraries for any of our products. You should not need to do anything special when developing a Rust application with Cargo, as the binding crate should by default handle the paths to the shared libraries per platform in the downloaded crate directory. If this is not the case please let me know, as that would be a legitimate bug. 

However, when shipping just your compiled Rust binary you WILL need to ship the shared libraries (from either the crate or from the GitHub repository) along with it, and make use of the the provided [builder method](https://docs.rs/pv_rhino/2.1.0/rhino/struct.RhinoBuilder.html#method.library_path) that lets you specify the path, in whatever way works best with you application.

**Comment by hellow554** [comment]
hey @ErisMik, thanks for your reply.

Unfortunately the source tells a different story: https://github.com/Picovoice/rhino/blob/e8d8f6179d25d911d2ace5a98d4ff15e2f13eb9a/binding/rust/src/rhino.rs#L25-L37

the library is loaded at runtime with a path specified at compile time and is later used to load the library functions here https://github.com/Picovoice/rhino/blob/e8d8f6179d25d911d2ace5a98d4ff15e2f13eb9a/binding/rust/src/rhino.rs#L236-L237

The build, that you mentioned does nothing with the library, except checking if it exists: https://github.com/Picovoice/rhino/blob/e8d8f6179d25d911d2ace5a98d4ff15e2f13eb9a/binding/rust/src/rhino.rs#L331

I have a patch ready if you like. I could create a PR tomorrow fixing this for rhino and pvrecorder.

**Comment by ErisMik** [comment]
@hellow554 Excellent catch! This is definitely the incorrect behaviour and should be addressed right away. I'd love to take a look at your patch in a PR but we may go through with our own solution in the meantime.
