### ISSUE TITLE
Using custome wake words and custom contexts

### ISSUE THREAD

**Issue by arnamoy10** [Picovoice/rhino#31]
Hello,  We just created custom wake words and custom contexts and trained models using the account we have in the Picovoice console.  We would like to use these instead of the default ones supplied with the python demo.  I see that the following variables need to be customized:

- rhino_library_path=args.rhino_library_path
- rhino_model_file_path=args.rhino_model_file_path,
- rhino_context_file_path=args.rhino_context_file_path,
- porcupine_library_path=args.porcupine_library_path,
- porcupine_model_file_path=args.porcupine_model_file_path,
- porcupine_keyword_file_path=args.porcupine_keyword_file_path

We are able to figure out the rhino_library_path, rhino_model_file_path, porcupine_model_file_path, porcupine_library_path.  But what about the keyword file and context file, how do we get those files for the custom keyword and context we trained?

Thanks

**Comment by kenarsa** [comment]
keyword_file and context_file are what you trained on the console. the model paths dont need to change.
