### ISSUE TITLE
Rhino Issue: Use of 2 different language SDKs on the same device show up as multiple devices

### ISSUE THREAD

**Issue by tsgowtham** [Picovoice/rhino#320]
I was initially evaluating Rhino on Python before switching to Rust as pvrecorder was causing issues when I created an exe using pyinstaller. The picovoice console currently shows that I've used my access key on 2 devices.

### Expected behaviour
Picovoice console should have showed that the access key was used only one device.

### Actual behaviour
![image](https://user-images.githubusercontent.com/19857923/156929089-563beaf9-6a90-4407-a337-d86c626e8d7c.png)

### Steps to reproduce the behaviour
I can't try and reproduce this issue as I'll hit the device limit.
But I started of with the python example and a few days later I used the rust example.

**Comment by ErisMik** [comment]
Could you provide a few more details on the system setup you were using? If you were on Windows (I'm guessing based on the `exe`), was Docker or WSL involved in any way?

**Comment by tsgowtham** [comment]
Hi, I am using Windows. Docker and WSL were not involved in any way.

**Comment by ErisMik** [comment]
So far I have been unsuccessful in reproducing the issue, could you provide a few more details on the specific Windows, Python and Rust versions used? Additionally, it would help if you provided your AccessKey via EMAIL to eric@picovoice.ai, as I could then debug internally.

**Comment by tsgowtham** [comment]
Hi @ErisMik, I'm not able to recreate it now. My dashboard shows that I'm using only 1 device now. I tried running my python script and the Rust code and the count did not increase to 2. I guess your recent update to the dashboard fixed it?
Let me know if you would still want me to share my access key over email.
