### ISSUE TITLE
Bigger number support

### ISSUE THREAD

**Issue by jmagnette** [Picovoice/rhino#328]
**Is your feature request related to a problem? Please describe.**
I wanted to evaluate if Picovoice/Rhino could fit one of my projects, but encountered the issue that built-in, you can only specify numbers of 1 or 2 digits. 
The issue is I need to be able to specify a liquid quantity (something like "Pour 250ml of ...").
I was quite surprised that a $pv.integer or $pv.ThreeDigitsInteger did not exists. 
In the same time, "basic" units are also not supported (ml, cl, l, ...) and you must specify them in full letters in your slot (even if I do understand the complexity of understanding a short version of a word).

**Describe the solution you'd like**
It would be nice to be able to access 3+ digits numbers. For my case, 3 digits is enough as you can use the next unit, but decimals would be impossible. And it is sad that using "One Thousand 3 hundred and forty-seven" wouldn't give you 1347 as a result.

**Describe alternatives you've considered**
I tried creating a slot with the different number names above 99, but it is long and the intent detection result returns the number as text an not as a number => would need to do a clever parse afterward.

**Additional context**
For information, I was trying this in a French context, but I guess the issue woul be the same in English.
Only tried on the Pico Console, so through the web browser

**Comment by kenarsa** [comment]
I don't think we can include this in our immediate roadmap in the coming months, unfortunately. I am closing this right now but will re-open if priorities change on our end. You can obviously build these yourself using `slots`. i.e. autogenerate these slot values and import them via the `YAML import ` option in Picovoice Console. But I understand this is extra work.

**Comment by danube** [comment]
Wanted to receive an IP address, wich dies on the same end. @kenarsa how to autogenerate this, as numbers are not allowed in slots but have to write in words, i.e. "twohundred sixtythree"?
