### ISSUE TITLE
Ignoring input from a certain point on

### ISSUE THREAD

**Issue by SoPrecht** [Picovoice/rhino#331]
**Is your feature request related to a problem? Please describe.**

I am using rhino for my Bachelorthesis. I want to ignore the input from a certain point on. Easy Example: "I am SomeName". I don't need the name and want to ignore it.

**Describe the solution you'd like**
It would be nice to have a command to ignore all following input. That way, everything said after this, is irrelevant for calculating the intent.
I know this could be problematic with double expressions. "I am NAME" would yield the same result as "I am cold". In this case the ignore case could only be the outcome if others don't fit.

**Describe alternatives you've considered**
create a slot with every possible word suitable. But this would be of immense size.

**Additional context**
I am using the rhino sdk for Unity. I have UserInput like the Name that is defined per text form so I don't need like a wild card slot.

**Comment by kenarsa** [comment]
understood and appreciate the feedback. we don't have plans to add wildcard support to Rhino at this time. If that changes I will re-open this issue.
