### ISSUE TITLE
Free Activation Process

### ISSUE THREAD

**Issue by rickmini** [Picovoice/rhino#363]
Could you please tell me how the 3 free activations work. I have been using rhino and other picovoice librarys for personal development successfully for a few months. I have 4 different platforms/cpus that i am trying the same python code for.
My request is: How do I decommision one of the 3 activations, so that I can use it on a different cpu/computer.
If that is not possible, how do i know when the license renews, so that i can plan around it.
Thank you

**Comment by kenarsa** [comment]
each activation is valid for 30 days. it will be "decommissioned" automatically at the end of its validity.
