### ISSUE TITLE
Where/How does rhino do silence detection

### ISSUE THREAD

**Issue by irthomasthomas** [Picovoice/rhino#4]
Hello,

I'm playing with the demos and I'm very impressed so far. One thing I am missing though is how to do silence / break in speech detection? You must be doing so in the rhino coffee machine demo?

Thanks

**Comment by kenarsa** [comment]
Hello, Thank you. Rhino has some internal capability to detect the end of the speech. Is there a particular case you have issues with?

**Comment by irthomasthomas** [comment]
Hi kenarsa
To begin with, I was trying to modify your cheetah demo so that it would transcribe audio after a hotword. I can get it to trigger recording ok, but I don't know how to have it stop recording at the end of the speech.

**Comment by kenarsa** [comment]
Correct. Rhino has a builtin end of speech detection. For Cheetah, we decided to not provide that as a builtin feature as for a lot of use cases you don't want a speech to text engine to do that. You need to somehow create that yourself if you want to use cheetah for command and control.

**Comment by kenarsa** [comment]
Closing the issue. Reopen if needed, please.
