### ISSUE TITLE
How to I change the language for the generated intents etc in the Rhino console?

### ISSUE THREAD

**Issue by MatsGej** [Picovoice/rhino#432]
### What is the URL of the doc?
The console for Rhino

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
How do I change the language, right now it seem to only support EN

Also, in one place it is stated to Rhino can handle these languages:
Rhino supports English, French, German, Italian, Japanese, Korean, Portuguese and Spanish.
https://picovoice.ai/docs/faq/rhino/

in another place it is stated that it handles these
English, 
German,Deutsch
Spanish, Español
French,Français
Italian,Italiano
Japanese,日本語
Korean, 한국어
Portuguese, Português
Mandarin, 普通话
Dutch, Nederlands
Russian, Русский
Hindi, हिन्दी
Polish, Język polski
Vietnamese, Tiếng Việt
Swedish, Svenska
Arabic, اَلْعَرَبِيَّةُ
https://picovoice.ai/platform/rhino/

Which page is correct?

And what does "Every user still has access to unlimited voice interactions in all languages." on this page https://picovoice.ai/platform/rhino/   mean

**Comment by kenarsa** [comment]
@MatsGej in the future open a separate issue for each question please, OK?

- When you create a Rhino context you get to select the language.
- The ones in the dropdown are supported. The other ones are in the roadmap. 
- We don't charge per voice interaction (unlike Dialogflow).

**Comment by MatsGej** [comment]
Do you have an estimate date on the Swedish version?
