### ISSUE TITLE
Rhino Issue: Cannot Load Libraries with .NET Framework 4.6.1+

### ISSUE THREAD

**Issue by jeffpowell** [Picovoice/rhino#433]
I've attempted to use the Rhino library within a .NET Framework application, which the documentation says should work fine, but it keeps failing to load.  Is there something I'm missing?

### Expected behaviour
Libraries should load with .NET Framework 4.6.1+ (as indicated in the documentation).

### Actual behaviour
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

### Steps to reproduce the behaviour
Take the existing MicDemo.cs, and created a new Console project with .NET Framework 4.6.1 / 4.7.2.

Add via NuGet:  
Rhino 2.1.8, 
PvRecorder 1.1.1

Run with valid access key and context file.

**Comment by mrrostam** [comment]
To Solve this issue, may I know the platform (OS) you're using for Rhino?

**Comment by jeffpowell** [comment]
Windows 11, using VS 2022.

**Comment by jeffpowell** [comment]
This resolved the issue for me.  Thank you.

I already tried this in my project code, but I clearly had not tried this yet with my minimum reproducible example.
