### ISSUE TITLE
Rhino Issue: 

### ISSUE THREAD

**Issue by petercwallis** [Picovoice/rhino#452]
### Expected behaviour
On the Developer Console I was expecting $pv.TwoDigitInteger to match "thirty"

### Actual behaviour
Its behaviour seems to be the same as $pv.SingleDigitInteger and returns "3" when it works, if it does.

**Comment by kenarsa** [comment]
I does work and returns `30`. I cannot reproduce this issue. If you provide the YAML export of your context with utterances that cuases the issue we can try to reproduce.

**Comment by petercwallis** [comment]
Okay -yes it works. It matches SingleDigitIntegers as well so I did not
need the following:

set a $pv.SingleDigitInteger:time timer
set a $pv.TwoDigitInteger:tens $pv.SingleDigitInteger:units timer

A "check" button on the developer page would be more helpeful than having
the red warnings pop up with what appear random actions.

Also a "reset" button might be useful to save reloading the page ... I am
in the UK on a RPi4...

Thanks,
P
