### ISSUE TITLE
dynamic contexts would be good

### ISSUE THREAD

**Issue by petercwallis** [Picovoice/rhino#453]
My expertise is in what used to be known as "dialog managers" and certainly am trying something out of the box, however, it is a feature that is (was) available with VoiceXML

**Describe the solution you'd like**
I would like to be able to build rhino with several contexts (30 say??) which are deactivated, and then activate one (or more) depending on what is expected by my code. For example if the system asks a question, I would be great to be able to load the yes/no context.
It would also be useful to be able to rank the rest of the deactivated contexts (or at least some) if the yes/no context goes unrecognised.

**Describe alternatives you've considered**
What happens if I build several rhinos? I assume they all process the audio independently and my system will slow down proportionally -- assuming there is not a resource conflict that prevents this approach.

**Additional context**
I realise this is not what modern speech interfaces do, and that VXML was eventually unsuccessful, however if we want more out of speech interfaces then I believe this, or something like it, is a pretty basic requirement.

**Comment by kenarsa** [comment]
You can do all this with the SDK. You can create as many contexts as you want and initialise Rhino with one of them (i.e. activate it). Depending on the result, deactivate it and switch to any other one. If you run multiple rhinos concurrently, you need more CPU for sure. But if you run them sequentially, then you don't. As you said, this is part of `dialog management` logic. Rhino is NOT a dialog manager. You can implement yours on top of it.

**Comment by petercwallis** [comment]
Thanks for the prompt response.

Perhaps you could give me some example code that shows how to "activate"
and "deactivate" an instance of the Rhino class, rhino.  It of course needs
to activate and deactivate the audio processing as well (presumably).  That
this is possible was not clear to me from the API.

P

**Comment by petercwallis** [comment]
Okay. I didn't notice a destructor in the java API  - will look at other
languages.

 Can we keep "dynamic contexts" as something on the suggested improvements
list as it is a fairly standard requirement for writing a dialog manager.
P
