### ISSUE TITLE
Picovoice Console timeout

### ISSUE THREAD

**Issue by Patrick257** [Picovoice/rhino#460]
Hello,

I'm trying to build a rhino context (in German/DE) using Picovoice Developer Console. I began running into an "Internal Server Error" when saving the context. Upon experimenting, I found that the error occurs when trying to save a context with more than 32 intents.

Is there a hard limitation on the number of intents in a context or is this a bug?

In fact, if this works as designed, I would suggest to issue a more informative error message to the user. Also, the Rhino Speech-to-Intent Engine FAQ (first question) suggests there is no limitation.

Thanks!

**Comment by kenarsa** [comment]
@Patrick257, thanks for the report. Can you export the context and share the YAML file? This is probably a timeout issue that we are aware of. If that is the case, there is a fix for it, and we plan to release it in the coming weeks.

**Comment by Patrick257** [comment]
@kenarsa Thank you for your quick response! Did you by any chance change/fix anything already? I was trying to recreate the issue today to send you a YAML export of the context but at the moment I'm able to add intents beyond 32. In the past couple of weeks, I was not able to do that.

**Comment by ErisMik** [comment]
@Patrick257 It's a timeout issue depending on a few factors, so it's likely you've made some changes to your context since that are circumventing this issue. I'm linking https://github.com/Picovoice/picovoice/issues/474 as it's the same issue may have some additional details. I'll close both that ticket and this one once the fix is officially out.

**Comment by kenarsa** [comment]
@Patrick257, with the new release, the issue should be resolved. So, I am closing this, but please re-open it if you still experience the problem, and we will look into it as soon as possible.
