### ISSUE TITLE
add custom vocabulary

### ISSUE THREAD

**Issue by tempo-riz** [Picovoice/rhino#464]
Basically the same capability that leopard/cheetah models have : beeing able to add your own custom words
It is something planned ?
do you have any workaround ideas ?
Thanks !

**Comment by ksyeo1010** [comment]
I will bring it up with the team, but I can't give you an estimate on when this will be done. Will keep the issue open.

**Comment by kenarsa** [comment]
Unfortunately, this is not something we can prioritize at this time.
