### ISSUE TITLE
context file not found

### ISSUE THREAD

**Issue by eswar7981** [Picovoice/rhino#468]
i trained and downloaded the custom word model of pvrhino windows,but i am unable to locate context path into pvrhino model . i am using jupyter notebook.
rhino = pvrhino.create(
   access_key='${}',
   context_path=r'${D:\a\a.rhn}',
 

)
i am getting error as 'contextfilenot found'.

**Comment by ErisMik** [comment]
Based on the code snippet you've given make sure you are removing the `${}` from the examples, these are supposed to be replaced by your values:
```python
rhino = pvrhino.create(
    access_key='aaaabbbbccccdddddeeeffffggg',
    context_path='D:\a\a.rhn',
)
```

**Comment by eswar7981** [comment]
def get_next_audio_frame():
    return 

while True:
   audio_frame = get_next_audio_frame()
   is_finalized = rhino.process(audio_frame)
   if is_finalized:
      # get inference if is_finalized is true
      inference = rhino.get_inference()
      if inference.is_understood:
         
         intent = inference.intent
         slots = inference.slots


what changes should i make in above code

**Comment by eswar7981** [comment]
recorder = PvRecorder(device_index=0, frame_length=rhino.frame_length)
recorder.start()
if output_path is not None:
    wav_file = wave.open(output_path, "w")
    wav_file.setparams((1, 2, 16000, 512, "NONE", "NONE"))

    print(rhino.context_info)
    print()

    print("Using device: %s" % recorder.selected_device)
    print("Listening...")
    print()

    while True:
        pcm = recorder.read()
        if wav_file is not None:
            wav_file.writeframes(struct.pack("h" * len(pcm), *pcm))
            is_finalized = rhino.process(pcm)
            if is_finalized:
                inference = rhino.get_inference()
            if inference.is_understood:
                print('{')
                print("  intent : '%s'" % inference.intent)
                print('  slots : {')
                for slot, value in inference.slots.items():
                    print("    %s : '%s'" % (slot, value))
                    print('  }')
                    print('}\n')
            else:
                print("Didn't understand the command.\n")    



what is the outputpath in the above code i am unable give it.
