### ISSUE TITLE
rhinomodel

### ISSUE THREAD

**Issue by eswar7981** [Picovoice/rhino#469]
demo/python/rhino_demo_mic.py

what changes should i make in above code to make it work. i tried but did not worked.
i know that we have to add accesskey and contextfile path but i am getting error and is there any other changes to be made.

**Comment by ErisMik** [comment]
I suggest going through the [README](https://github.com/Picovoice/rhino/tree/master/demo/python) for the Rhino Python demo carefully, as it walks through how to use it correctly. Additional help can be found in the [Quick Start](https://picovoice.ai/docs/quick-start/rhino-python/) or [API](https://picovoice.ai/docs/api/rhino-python/).

These issues are intended to be used for legitimate issues within the Picovoice platform and engines. In the future, please provide details on environment, code used, and the specific error that you run into when opening an issue.
