### ISSUE TITLE
pvrhino_demo_mic

### ISSUE THREAD

**Issue by eswar7981** [Picovoice/rhino#470]
import pvrhinodemo
from pvrhinodemo import rhino_demo_mic

!rhino_demo_mic --audio_device 0 --access_key ssdsdd --context_path D:/a/a.rhn

why i am not getting any output or error from above code.
i want to print the intents of spoken words

**Comment by ErisMik** [comment]
These issues are intended to be used for legitimate issues within the Picovoice platform and engines. In the future, please provide helpful details on environment, code used, and the specific error that you run into when opening an issue.
