### ISSUE TITLE
Attempt to renew a license nearing expiry was unsuccessful

### ISSUE THREAD

**Issue by Enc3ph4l0n** [Picovoice/rhino#472]
### Expected behaviour

License should renew.

### Actual behaviour

License doesn't renew. I temporarily cleared the existing license and reponds with "activations exceeded".

### Steps to reproduce the behaviour

I'm bemused by this. I have used my key on 1x Linux PC and 2x RPi. I'm no longer using PV packages on the Pis and haven't done so for some days now (although I acknowledge the 30 day reset period), but I have been using the Linux PC for weeks now and continue to do so.

As of this morning, after downloading a revised Rhino model from the console, I restarted my script and the Linux PC is unable to renew the license. License renewed several times yesterday without issue (having restarted my script several times). 

No significant OS updates have been installed, Rhino (npm package) hasn't been reinstalled (would this matter anyway? - I found uninstalling/reinstalling Porcupine on one of the Pis caused this same problem - but is a non-issue because as said I won't be using the Pis going forward). The PC hasn't been restarted for 26 days. IP hasn't changed. I've no idea why it's now being recognised as a 'new device' that's needs to be activated.

Can you provide any insight to other factors/meta that would cause Rhino to see the Linux PC as a new 'thing' all of a sudden?

Thanks!

**Comment by mrrostam** [comment]
You should be able to restart your script without any issues as long as the number of the activated device for your AccessKey is lower than the limit. To debug this further, can you send your AccessKey or email used to sign up for Picovoice Console to [hello@picovoice.ai](mailto:hello@picovoice.ai)?

**Comment by Enc3ph4l0n** [comment]
Hi @mrrostam. Thank you for your reply. That's the behaviour I've seen up until today. I emailed about 4 hours ago with the subject: Query -  AccessKey reached its device limit.

Forgive me, it felt like a chicken/egg situation where if I emailed then I would be asked to raise it here and vice-versa - hence why I've opened this issue just in case the email wasn't the right approach.

Thank you!

**Comment by mrrostam** [comment]
We have identified the issue and are working on a fix for it. Sorry for the inconvenience; will circle back to you once the fix is in prod.

**Comment by Enc3ph4l0n** [comment]
Working as expected now. Thank you for the quick resolution!
