### ISSUE TITLE
Always prompting “Make sure your access key ' is a valid access key.” error

### ISSUE THREAD

**Issue by o2dp** [Picovoice/rhino#496]
Hello,

I am try to use your unity demo, I found a very strange problem, if I use the original rhn model  "smart_lighting_windows.rhn" in your demo, it works fine, but if I change to a custom rhn [Move_windows_v2_2_0.zip](https://github.com/Picovoice/rhino/files/11220549/Move_windows_v2_2_0.zip) downloaded from the website https://console.picovoice.ai/rhn, it just prompts " Make sure your accesskey is a valid access key". The only difference between them is the rhn model. I also tried to generate rhn using the yaml in [your documentation](https://github.com/Picovoice/picovoice/blob/master/demo/unity/README.md), but it doesn't work either.

I would like to ask if this rhn is bound to accesskey? Or is there a limit for new users?

Thanks.

**Comment by kenarsa** [comment]
Which version are you using? Are you entering your `AccessKey` from Picovoice Console?

**Comment by o2dp** [comment]
unity package version is rhino-2.1.4. Yes, i copied from Picovoice Console.

**Comment by kenarsa** [comment]
OK. Can you please use the latest (`2.2.0`) and re-download the model from Console? I suspect this is a version mismatch, but the error message is misleading in this case.
