### ISSUE TITLE
$pv.TwoDigitInteger in Polish

### ISSUE THREAD

**Issue by darys58** [Picovoice/rhino#498]
Testing Rhino in Polish. Numbers 10 and above in $pv.TwoDigitInteger have a value of 1 less than they should.

**Comment by bejager** [comment]
@darys58 , thanks for reporting. We are pushing a fixed version asap.

**Comment by bejager** [comment]
The issue should be resolved with the latest version. I am closing this but please re-open it if you still experience issues.
