### ISSUE TITLE
Using context file created from console gives Segmentation fault in pvrhinodemo

### ISSUE THREAD

**Issue by jeffbonasso-ambifi** [Picovoice/rhino#51]
I have created a context file in the console and published the model for a Raspberry Pi. I have a Raspberry Pi 4. I am trying to use the pvrhinodemo to test the context file. I get the following error...

![IMG_3050](https://user-images.githubusercontent.com/38217156/100529076-9002b100-31b1-11eb-88a9-367fb1e7e382.JPG)

This is the rhn file trying to use.

[checklist_raspberry-pi_12_27_2020_v1.5.0.rhn.zip](https://github.com/Picovoice/rhino/files/5611444/checklist_raspberry-pi_12_27_2020_v1.5.0.rhn.zip)

**Comment by kenarsa** [comment]
Thanks for reporting this. The issue was on our side. We identified and resolved. Can you please go ahead and train the model again? It should work. Please keep us in the loop.

**Comment by jeffbonasso-ambifi** [comment]
Thanks for the quick support! It is now working.
