### ISSUE TITLE
Rhino Issue: Vue and Web demos: Node runtime error in script "start"

### ISSUE THREAD

**Issue by Fuchssystems** [Picovoice/rhino#531]
### Expected behaviour
Node script "start" should not throw an error

### Actual behaviour
Node script "run start en" throws the error:

> rhino-vue-demo@2.2.0 start
> node scripts/run_demo.js en

node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn npx ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npx',
  path: 'npx',
  spawnargs: [ 'vite' ]
}

Node.js v18.16.1

### Steps to reproduce the behaviour
git clone --recurse-submodules https://github.com/Picovoice/rhino.git
cd rhino/demo/web
npm install
npm run start en

Platform: Windows 11 64 Bit on i5 12th generation
Node v18.16.1
NPM 9.41

**Comment by Fuchssystems** [comment]
The script "run_demo.js" fails within the last command.
Executing in the terminal:
npx vite
starts the development server as expected.

So the problem is that "npx" is not found.
npx is installed globally (version 9.4.1)

Maybe adding the path to npx to the environment variables of windows would fix the problem.
Node/npm was installed with the .msi installer.

**Comment by Fuchssystems** [comment]
Fix:
On windows npx has to be called with "npx.cmd".
Just replace "npx" with "npx.cmd" at the end of the script file:

child_process.fork("vite", commands, {
  execPath: "npx.cmd",
});

**Comment by ksyeo1010** [comment]
Noted, we will be pushing the fix for windows later on.

**Comment by ksyeo1010** [comment]
Demos has been updated: https://github.com/Picovoice/rhino/pull/564
