### ISSUE TITLE
Rhino Issue: not able to find intent

### ISSUE THREAD

**Issue by waseemAnsari11011** [Picovoice/rhino#55]
i am running picovoice rhino demo for react-native i have given a context to it which contains : 30-40 words its like a 3-4 line sentence that i have inserted as my context. 

![IMG_20201212_121453](https://user-images.githubusercontent.com/72751386/101977549-1d470a80-3c74-11eb-87f5-3507855db856.jpg)

what is happening is when i am trying to say the exact same sentence which is there in the context  inserted by me it is sometime showing "isunderstood" : false, even if i am resiting the exact same sentence it is not able to find the intent 'sometimes' why is this happening and how to overcome this challenge?

![Screenshot_2020-12-12-12-09-11-084_ai picovoice reactnative rhinodemo](https://user-images.githubusercontent.com/72751386/101977565-3485f800-3c74-11eb-8f1a-c0c2e6f4620a.jpg)

Also can you tell me how the rhino speech to intent is actually working is it first converting the speech to text and then using NLU to find out the intent?

**Comment by kenarsa** [comment]
I don't know why you are not getting the intent back. But what are you trying to achieve?

As a test can you try the react-native demo on repo and make sure that works for you?

**Comment by waseemAnsari11011** [comment]
can you tell me how rhino is able to find the intent? how it works?

**Comment by kenarsa** [comment]
Can't tell you about how it works. That is proprietary.
