### ISSUE TITLE
ACTIVATION_LIMIT_REACHED during evaluation without network traffic

### ISSUE THREAD

**Issue by Fuchssystems** [Picovoice/rhino#571]
Evaluating Rhino and did a web page to count tyre inventory by size using Rhino speech to intent.

Problem: getting error 'pv_rhino_init' failed with status ACTIVATION_LIMIT_REACHED'
after doing:

- devolopment with the Vite development server (Vue, Quasar) (still works)
- build a 'dist' version to be served
- uploaded to 1st webspace under a subdomain, however the SSL certificate is not valid for subdomains so google Chrome does not allow use of the microphone.
- set up a free MS Azure static website with https to enable the microphone
- and additional served on development machine with node http-server

Now only the local development server works and the other setup have ACTIVATION_LIMIT_REACHED.

Do not understand how exactly a user (for the limitation) is defined.
Is it a browser window or a web server or a human voice?

If I have to wait 1 month to try again: nice, but can not evaluate this way.

**Comment by ksyeo1010** [comment]
The error means you have used all the devices and yes you need to wait a month. Using Rhino outside your development server will count towards your number of active devices.
