### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/rhino-react-native/)

### ISSUE THREAD

**Issue by Hamid-faizan** [Picovoice/rhino#577]

**Comment by adigujjar** [comment]
https://picovoice.ai/docs/api/rhino-react-native/

**Comment by ksyeo1010** [comment]
We need to know what is the specific issue in order to help.

**Comment by petercwallis** [comment]
So how long do you think it takes a member of your target market to run a demo?  I have done this twice now and it has not got any better.  Can I suggest you find a second year computer science undergrad (who has not used your system before) and see how long it takes for him or her to run a demo.  Indeed why not record the session to identify the mis-steps they take.  For your system I think it should not take more than half an hour to run a demo now that I've done it (twice), but I think you'll find it is currently more like half a day. The website is very much designed to sell the product, but having done that, the site needs to help us.

**Comment by mrrostam** [comment]
> So how long do you think it takes a member of your target market to run a demo? I have done this twice now and it has not got any better. Can I suggest you find a second year computer science undergrad (who has not used your system before) and see how long it takes for him or her to run a demo. Indeed why not record the session to identify the mis-steps they take. For your system I think it should not take more than half an hour to run a demo now that I've done it (twice), but I think you'll find it is currently more like half a day. The website is very much designed to sell the product, but having done that, the site needs to help us.

Firstly, it would be helpful if you could specify which demo you are referring to. Your comment pertains to a "closed" issue without clear context, making it challenging for us to assist/answer you accurately.

Regarding our demos, we've designed comprehensive resources to facilitate a smooth experience for developers. We offer platform-specific demos on our GitHub repository, each accompanied by detailed `README` files to guide users through the process. For instance, our Rhino demo for React-Native, which is in the issue's title, includes:

[Demo Repository](https://github.com/Picovoice/rhino/tree/master/demo/react-native)
[Quick Start Guide](https://picovoice.ai/docs/quick-start/rhino-react-native/)
[API Documentation](https://picovoice.ai/docs/api/rhino-react-native/)

These resources are designed to assist developers in quickly and efficiently understanding our products, typically within an hour or less. We encourage you to explore these guides, and if you encounter any specific issues during your demo setup, please feel free to open a new issue for it.
