### ISSUE TITLE
Define hardcoded/prefilled slots

### ISSUE THREAD

**Issue by Jonas2OO3** [Picovoice/rhino#61]
Hi,

I'm controlling my Spotify streaming via Picovoice. I have expressions in the form `music $musiccommand:command` where the command can be something like 'play', 'pause', 'next', 'previous'.

Now some commands need extra parameters, like 'shuffle' (on/off), 'volume' (double digit integer). I want to use the same intent for that, and the code for that intent expects the `command` slot to be there. Therefore, for now, I also define the expressions `music $musiccommand:command $pv.SingleDigitInteger:volumelevel` and `music $musiccommand:command $state:state`.

Now I could also say `music play off` which does not make sense. So what I would like to do is define an expression like `music shuffle:command $state:state` or `music volume:command $pv.SingleDigitInteger:volumelevel`, basically defining hardcoded values for the slots instead of using a list of possible values.

Of course I could define extra slots for shuffle/volume, but this way it would make things much easier.

Generally, Picovoice with Respeaker on Raspi - awesome!

**Comment by kenarsa** [comment]
Thanks for the feedback. This is very interesting. Is the code somewhere on GitHub? I'm really keen to check it out. Do you use Spotify's public API? 

Back to your question ... I think you should break your intents to be more granular. I suggest having an intent just for setting the volume, one for turning shuffle, and one for generic commands that do not need extra arguments. This is essentially a design challenge and hence no right or wrong answer.

**Comment by Jonas2OO3** [comment]
Hi,

yeah, I'm using [spotify-web-api-node](https://www.npmjs.com/package/spotify-web-api-node) which basically seems to be a wrapper for the Spotify API. I'm running [raspotify](https://github.com/dtcooper/raspotify) on the same Raspi 4 (4GB) that Picovoice/Respeaker are on.

The code is not uploaded anywhere yet, but it's really not that much. I added the code to a gist (and did some cleaning up, I hope I didn't break anything): https://gist.github.com/Jonas2OO3/467bcf346eaf220a39f5470774fe1d1c

First you run `node authorize.js`, then `node api.js`. After running it once, you'll get a list of your devices in the log messages. Find the one you want to set as a fixed device and add the ID to `device_id.txt`, then again `node api.js`.

Its a separate program that I then spawn from my actual node code that reacts to Picovoice commands and I communicate via stdin. Not sure why I did that though .... ;)

```javascript
oMusicCtrl = require('child_process').spawn('../spotify/api.js', {
    cwd: '../spotify',
    detached: false,
});

const osIntentCommandToSpotifyFunction = {
    next: 'skipToNext',
    previous: 'skipToPrevious',
    shuffle: 'setShuffle',
    volume: 'setVolume',
};

// ... setup pico voice etc ...

if (oIntent.intent === 'sendMusicCommand') {
    // some more half-generic code to handle parameters, like converting 'on'/'off' to true/false or '50%' to 50
    
    oMusicCtrl.stdin.write(`{ "command": "${osIntentCommandToSpotifyFunction[oIntent.slots.command]}" }\n`);
}
```

The nice thing is that I can use that to pause the music (or turn the volume down) whenever a wake word is recognized, and resume afterwards.

**Comment by kenarsa** [comment]
super cool! thanks a lot. Closing the issue at this point as we don't have current plans to introduce automatic type casting. But if that becomes a part of roadmap I will comment here. Thanks for sharing.

**Comment by Jonas2OO3** [comment]
Follow-Up question: is it at least possible to find out what intent expression did match? Or some details about optional parts of the expression that were said or not?

For example, I'd like to do expressions like `music volume $pv.SingleDigitInteger:volumelevel` and `music volume $pv.SingleDigitInteger:volumelevel for this song` (or `music volume $pv.SingleDigitInteger:volumelevel (for this song)`) but it seems like there's no way to find out if `for this song` was said or not?

**Comment by xbrtll** [comment]
Couldn't you simply use different slot variables, i.e. `music volume $pv.SingleDigitInteger:volumelevelAll` and `music volume $pv.SingleDigitInteger:volumelevelSong for this song`?
