### ISSUE TITLE
Set explicit slot phrase values

### ISSUE THREAD

**Issue by Jonas2OO3** [Picovoice/rhino#62]
Hi,

I want to keep the code that processes the intents as generic as possible. As described in #61, I am controlling Spotify via its API. Right now I have commands like `music play` or `music pause`, and then I am using `spotifyApi[intent.slots.command]` to call the according method on the Spotyify API. However, the command to skip to the next song is _skipToNext_, in the voice command I'd like to say `music next`.

Would it be possible to configure slot phrase values for each phrase defined in a slot? In the best case, I could even define if its a string, a boolean or a number (e.g. for the _shuffle_ command, where I'd like to convert `"on"` to `true` and `"off"` to `false`), and the same is true for volume levels (`music volume low` or similar that I'd like to translate into an integer). If a separate slot phrase value is available, that could then be available in `intent.slot_values.xyz`. That way, I could have slot names like `param_1`, `param_2` that I automatically pass into the Spotify API functions when present in a intent.

The advantage is that I'd only have to cange the Rhino config in the cosole, and not touch my intent processing code, to add a new Spotify API voice call. Hope that makes sense.

Jonas

**Comment by kenarsa** [comment]
We don't have that extra level of indirection. This should be fairly trivial do accomplish on the application side.
