### ISSUE TITLE
Processing crashes on some commands

### ISSUE THREAD

**Issue by xbrtll** [Picovoice/rhino#63]
For some context: I'm writing a Java program (running on Windows) that combines Porcupine and Rhino, i.e., listens for a wake word and passes to Rhino to interpret a single command. I tried to test it with the smart lighting demo context and an extended model that is based on the smart lighting one; both show the same problem.

When I say "Turn light in the kitchen to blue.", the program crashes somewhere inside the Rhino.process(short[] pcm) method and only the message "Process finished with exit code -1073740940 (0xC0000374)". No Java Exception/Error is thrown, so I think it has to be in the native code. The odd part is that similar commands like "Turn light in the kitchen to green." or "Turn light in the bathroom to blue." work fine and are interpreted correctly...

Do you have any hints as to what could cause this issue or is there any more useful information I should provide?

**Comment by kenarsa** [comment]
Can you please provide the context file (.RHN) you are using? Also please provide information on how you are running this in detail so we can reproduce.

**Comment by xbrtll** [comment]
Thank you for your reply! I put the code into a (currently private) github-project and sent you an invite link.

**Comment by kenarsa** [comment]
@xbrtll  thanks for reporting the issue and information provided. It should be fixed now on the mainline via #64 
Let me know if you still experience the issue otherwise I appreciate if you can close the issue if resolved.

**Comment by xbrtll** [comment]
Thank you very much, works perfectly now!
