### ISSUE TITLE
Rhino Issue: initialization error when use 3.0.0 params.pv

### ISSUE THREAD

**Issue by zshnb** [Picovoice/rhino#631]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
running success

### Actual behaviour
my code is
```
window.rhino._worker = window.rhino._worker || await RhinoWorker.create(window.rhino.key, {
            publicPath: 'rhino_medicine.rhn',
            forceWrite: true,
            customWritePath: "3.0.0_medicine.rhn",
        }, window.rhino.rhinoInferenceCallback, {
            publicPath: 'rhino_params.pv',
            forceWrite: true,
            customWritePath: "3.0.0_rhino_params.pv",
        });
        await WebVoiceProcessor.subscribe(window.rhino._worker);
```
and then I load the webpage, there is a error in console:
Uncaught (in promise) RhinoRuntimeError: Initialization failed: 
  [0] License is expired.
  [1] Failed to allocate, out of memory.
  [2] Failed to load context with `OUT_OF_MEMORY`.

### Steps to reproduce the behaviour
full js code
```
import { WebVoiceProcessor } from "@picovoice/web-voice-processor";
import { RhinoWorker } from "@picovoice/rhino-web";
import Rhino_params from './rhino_params.js'
import Rhino_medicine from './rhino_medicine.js'

// a global 'vaadinPorcupine' integration instance is enough
window.rhino = window.rhino || {
    key: null,
    async start() {
        console.log('Starting intent');
        console.log(`key: ${window.rhino.key}`)
        window.rhino._worker = window.rhino._worker || await RhinoWorker.create(window.rhino.key, {
            publicPath: 'rhino_medicine.rhn',
            forceWrite: true,
            customWritePath: "3.0.0_medicine.rhn",
        }, window.rhino.rhinoInferenceCallback, {
            publicPath: 'rhino_params.pv',
            forceWrite: true,
            customWritePath: "3.0.0_rhino_params.pv",
        });
        await WebVoiceProcessor.subscribe(window.rhino._worker);
    },
    async stop() {
        console.log('Stopping intent');
        await WebVoiceProcessor.unsubscribe(window.rhino._worker);
    },
    rhinoInferenceCallback(inference) {
        console.log(`inference: ${JSON.stringify(inference)}`);
        if (inference.isFinalized) {
            if (inference.isUnderstood) {
                const intent = inference.intent;
                const slots = inference.slots;
                const e = new CustomEvent("voice-intent",
                    { intent, slots });
                document.body.dispatchEvent(e);
                // take action based on inferred intent and slot values
            } else {
                // handle unsupported commands
            }
        }
    }
}
```
(Include enough details so that the issue can be reproduced independently.)

**Comment by ksyeo1010** [comment]
Based on the error you got, you got an out-of-memory error. Are you running your app in a memory-constrained environment? Which browser are you using to run this? Is your rhino context empty?

**Comment by zshnb** [comment]
> Based on the error you got, you got an out-of-memory error. Are you running your app in a memory-constrained environment? Which browser are you using to run this? Is your rhino context empty?

I use vaadin framework to run as a web in Chrome

**Comment by zshnb** [comment]
I try again with download rhino_params.pv in branch v3.0, and download a new context model, it's now working, but I don't know why it's work. In your docs now, the rhino_params model download link is still 2.2.0, it's not compatible with lib 3.0 and context model 3.0, I think you need to fix these problems

**Comment by ksyeo1010** [comment]
The orginal issue, I do think you ran out of memory since there is no other explanation, good it is working now. We just completed the v3.0 release so everything, including docs, should be up to date.
