### ISSUE TITLE
Rhino Documentation Issue

### ISSUE THREAD

**Issue by SuperJonotron** [Picovoice/rhino#65]
### What is the URL of the doc?
https://github.com/Picovoice/rhino

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
The note here about self service "self-service. Developers can train custom models using Picovoice Console " paired with the 30 day expiration shown in the console is unclear to me  what is possible in the free model.  Is the free model only available to be downloaded in that 30 day window or does it actually expire in use every 30 days and need to be retrained and installed?  I don't seem to see any other options to create custom models outside of the console at this time so I am not sure if that is a possibility either.

**Comment by kenarsa** [comment]
Correct. You need to press the train button every 30 days and reinstall the model. Is this hassle? Yes! Is there a plan to remove it? Yes, but I can't commit to a timeline, yet.

**Comment by SuperJonotron** [comment]
Understood.  Just starting to dip my toes into the picovoice world and wanted to make sure I understood all the restrictions.  Thanks for the clarification.  Looking forward to when this restriction is removed.

**Comment by jamiebikies** [comment]
Just checking in on this issue - has there been any movement on lifting the 30 day personal use expiry? I am just trying to make a small project for my home and picovoice could work well.

**Comment by ReeceKenney** [comment]
Also curious to hear if there has been any progress here. I have a personal project that works great with Picovoice but the 30 day expiration and 1 device limit is just far too restrictive for me to be able to use it.

I'd love if there was some sort of personal-premium level where we could pay for a less retrictive personal use (e.g. no expiration on the custom wake words and a larger device limit).
