### ISSUE TITLE
Rhino Documentation Issue

### ISSUE THREAD

**Issue by sim0wastaken** [Picovoice/rhino#659]
https://picovoice.ai/docs/faq/general/

I understand how the usage data is tracked, but I do not understand how this information is gathered and sent to the developer console

Our enterprise is in the process of evaluating Picovoice performance and solutions and while we are happy with the results we are seeing in our test implementations, the possibility for Picovoice models to work seamlessly without any internet connection is a decisive factor
More on that, I would simply like to know:
"Will my application which implements a couple of Picovoice models, including Rhino, also work without any internet connection?"

**Comment by ksyeo1010** [comment]
Your model will work for 30 days offline after activating, this will need to be done every 30 days to maintain functionality. If you require dedicated support, you can take a look at [Enterprise Support Add-on](https://picovoice.ai/professional-services/).
