### ISSUE TITLE
Server URL for AccessKey Whitelisting

### ISSUE THREAD

**Issue by James-Shared-Studios** [Picovoice/rhino#660]
I am writing to express my interest in trying out Picovoice Rhino for a project I am currently working on. I would like to understand the process for validating the AccessKey and how usage consumption is reported, especially since Rhino operates offline. Could you please provide information on the following:
1. **Server URL for AccessKey Whitelisting**: To ensure smooth integration and compliance with my network’s security policies, I need to know the specific server URL(s) that should be whitelisted for validating the AccessKey.
2. **Usage Reporting**: How is usage consumption tracked and reported for offline usage? Is there a specific endpoint or service that I should be aware of for this purpose?

Additionally, I would appreciate any guidance or resources you could provide for a first-time user of Picovoice Rhino to help me get started effectively.

Thank you for your assistance.

**Comment by hellow554** [comment]
Hey @James-Shared-Studios
Please don't ping people out of the blue.
I'm not affiliated with the company nor have any insight information on their products. I just happened to contributed some code to this repository.
Please avoid that in the future.

**Comment by hellow554** [comment]
If you just want to know the server URL you can use wireshark or any other network monitoring tool to get that. Maybe that can help you

**Comment by James-Shared-Studios** [comment]
> with Rhino

<img width="889" alt="image" src="https://github.com/Picovoice/rhino/assets/139377980/f9dec355-92ab-43f6-80e7-7544b2d7deb7">

Thank you for the information. However, I'm facing a specific challenge: without being able to whitelist your backend server URL for validating the AccessKey, I'm unsure how to proceed with trying Rhino. I'm experiencing a technical issue that's hindering my use of your product, which I consider a bug. Could you please confirm if https://kmp1.picovoice.net/ is the URL I need to whitelist? Your assistance is greatly appreciated. Thank you.

**Comment by hellow554** [comment]
As already said, I'm not part of the company. I have no clue what they are doing nor what needs to be done to make that work.
But I would start from there what you have done so far. Looks promising.

**Comment by James-Shared-Studios** [comment]
> As already said, I'm not part of the company. I have no clue what they are doing nor what needs to be done to make that work. But I would start from there what you have done so far. Looks promising.

so sorry Sir, that message was sent to @ksyeo1010 not you, apologize for the confusion.
