### ISSUE TITLE
Way to add multiple contexts?

### ISSUE THREAD

**Issue by Millertime72** [Picovoice/rhino#663]
Hi,

I was wondering if there is currently any way for me to add multiple contexts to a Rhino instance. My use case is that I am creating a project with multiples 'apps', and while I'd like to provide a separate context for each app, I would also like to include some base features for every app, such as a 'stop' intent, or a 'nevermind' intent. Currently, I am copy pasting these intents from one context to another. It would be nice to have a 'base.rhn', as well as one specific to each app.

I understand that some issues preventing this feature might be clashing intents between contexts, and the inability to parse for them once the contexts are exported. An alternative would be a way to import a .yaml file to overwrite only intents existing in said yaml, so that I could create a base context, export it, then import it into a different context without overwriting the unrelated intents.

Thanks for providing such a dependable service, I really enjoy using it.

**Comment by mrrostam** [comment]
Hi @Millertime72 

It's not possible to add multiple contexts for a single instance of Rhino. However, you can initiate different instances with various contexts and input the audio to each of them to achieve the same result (you might need to utilize the [reset API](https://picovoice.ai/docs/api/rhino-python/#pvrhinorhinoreset)). This approach grants more control over conflicting situations by prioritizing the 'base' model over others. Nevertheless, running multiple Rhino instances can escalate CPU and memory usage.

Regarding editing the yml file, I'm not entirely clear on your suggestion about importing and exporting, as Picovoice Console already supports both functions. From what I understand, you can effortlessly export your 'base' model, add new intents, and then import the updated yml file as a new context in Picovoice Console.

**Comment by Millertime72** [comment]
Thanks, the use of multiple Rhino contexts will solve my problem perfectly. As for the yml file, I meant to say that when I have an existing context and import a yml file, it might solve my problem if it were possible to only overwrite intents included in the yml file, not replace the entire context. However, your solution is much better.

Thanks again.

**Comment by mrrostam** [comment]
Ah, I understand. Currently, the Picovoice console doesn't have a "merge" feature for importing YML files.
