### ISSUE TITLE
Query on Using Latest Rhino Context Files with Older Library Version for Personal Project

### ISSUE THREAD

**Issue by ronspeclin** [Picovoice/rhino#680]
Hi Pico Team,

I'm currently engaged in a personal project involving a car headunit running on Android 4.3. Due to hardware limitations, upgrading the Android OS isn't an option. For this project, I'm experimenting with an older version of the Rhino library for speech-to-intent processing, using demo contexts.

I'm reaching out to inquire about the compatibility of using the latest context files generated from the Picovoice Console with this older version of the Rhino library. Given the project's specific nature and the constraints posed by the operating system:

Are there any compatibility considerations or specific steps I should follow to integrate the latest .rhn files with an older Rhino library?

Your guidance on this matter would be invaluable to me, and I wanted to take a moment to express my appreciation for your wonderful service. The innovation and support provided by the Picovoice team have been instrumental in enabling developers like myself to bring our ideas to life, even on constrained platforms.

Thank you very much for your time and assistance.

**Comment by mrrostam** [comment]
@ronspeclin Unfortunately, there is no way at the moment to obtain a custom context from Picovoice Console for the previous versions of Rhino
