### ISSUE TITLE
Can Rhino simply returnwhat is spoken

### ISSUE THREAD

**Issue by obrienj970** [Picovoice/rhino#681]
I'm curious if I can build an intent for Rhino that simply returns what was spoken after the wakeword.

I ask because that  would be simpler and less painful than starting with picovoice and replacing Rhino with Cheetah.  This is for a app that processes unformatted commands.  For example:

> jarvis find  ....any random address or query string...

BTW, this will all be done using Java for a tablet running Android 14.

Regards,
Jim

**Comment by ksyeo1010** [comment]
Rhino is not meant to be used as speech to text, the alternative would be if your search is limited you could add all of them.
