### ISSUE TITLE
Able to generate rhn context files from the client?

### ISSUE THREAD

**Issue by rhinocerbus** [Picovoice/rhino#684]
Hey all, quick question:

In the console, when creating a context file, I see you can import from a yaml file. Is it possible to do that from a client app, either through an API or manually given a yaml file built for supporting dynamic slot values, etc.? Haven't seen anything so far suggesting you can but figured it was worth asking.

Thanks!

**Comment by ErisMik** [comment]
@rhinocerbus  - thank you for your interest. Unfortunately, this is not currently possible with Rhino and is not a feature on our immediate roadmap. However, if you are an enterprise user, please reach out to us via email and we can see what solutions are possible.
