### ISSUE TITLE
Console account deleted

### ISSUE THREAD

**Issue by ar13pit** [Picovoice/rhino#691]
Dear Picovoice Team,

I didn't want to contact you over this forum, however I'm forced to due to not receiving any response from you.

My team (TechUnited Eindhoven) uses Picovoice for Robocup@Home and has created and maintains picovoice_ros package (https://github.com/tue-robotics/picovoice_ros), which you have publicly acknowledged on various social media channels as well. You have deleted our accounts which has caused a loss of our data and a complete freeze of the use of Rhino with our robot HERO, severely affecting our ability to perform any speech recognition tasks for Robocup@Home. Ever since we have switched to Picovoice, we have been a very public advocate of Picovoice. 

However, ever since you deleted our accounts without informing us, we have reached out to you multiple times using the contact form, yet have got no response. You have also labeled our accounts as "burner accounts". If you are no longer interested in us developing and maintaining the picovoice_ros package and are no longer supporting academic research projects, kindly make your position about it clear and we will stop advocating for using Picovoice!

Kindly do something about this and not let our opinion about Picovoice change as we love this library! However, if we are forced to switch to a new solution when our tournaments are so close, the image of Picovoice will forever be tarnished for us and we will recommend all of our fellow competitors (most of whose current and past members also have positions with big tech firms) to never use this library.

Sincerely,
Arpit Aggarwal
on-behalf of TechUnited Eindhoven,
Eindhoven University of Technology

**Comment by ksyeo1010** [comment]
We can see the issue, next time only open on one repository.
