### ISSUE TITLE
Rhino C code on Rpi unable to parse the wav file

### ISSUE THREAD

**Issue by AniketJangam** [Picovoice/rhino#7]
Hello Alireza,
I am experimenting with Rhino and tried it on RPi-3. It takes input from the test_within_context.wav file from audio_samples and returns the detected intent. I recorded few more audios in same format and expected rhino to understand the intents. But it could just give slots, slots_value output for one of the audio files. The rest of three audio wav files are not understood by Rhino despite being recorded in the  same environment as the  one being understood. What might be the error?

Comparing it with Snips: Snips is able to understand my voice commands spoken in the same environment. So, it makes me believe that my voice commands and noise should not be an issue.
Please guide.

Thanks!

**Comment by kenarsa** [comment]
is the same command in all files? hard to say without having the files ...

**Comment by AniketJangam** [comment]
Yes.
Your command is "Can I have medium sized double shot Americano with lots of milk and some sugar?"
I rephrased it to  "Can I have medium sized double shot **Latte** with lots of milk and some sugar?" which was understood. Then I tried
"Can I have medium sized **single** shot Americano with lots of milk and some sugar?"      and
 "Can I have medium sized double shot Americano with **some milk** and some sugar?"
but none of these other two were detected.

**Comment by kenarsa** [comment]
you need to somehow attach your WAV files to the issue. otherwise, I can't help.

**Comment by AniketJangam** [comment]
Sure. Here is the link to Google Drive where I have the audio files I am talking about.

https://drive.google.com/drive/folders/1pNgeoL0ytUbL001-H2B4wgSE46lIOJCl?usp=sharing

**Comment by kenarsa** [comment]
You need to have a couple of seconds of silence after the command for the rhino to finalize. please re-record with more silence. Also it seems like your microphone is cutting high frequency content

**Comment by AniketJangam** [comment]
The couple of seconds at the end of the command did not help. May be I will have to find a way to get it to record the higher frequency and see how Rhino responds to that audio file. I would close this issue for now and get back to you if the problem still persists.
