### ISSUE TITLE
date and time as built-in slots

### ISSUE THREAD

**Issue by krem-cheese** [Picovoice/rhino#70]
Hi, 

I am using rhino to create a model for scheduling a helper. Based on a task and a timing, it should extract what that task is and the date and time as intents. I am having trouble with this and cannot find any resources online to guide me through adding time and date as slots, which normally would be regular expressions. Any advice/guidance?

Thanks

**Comment by kenarsa** [comment]
time and date are not builtin slots now. You can create them yourself using other built-in slots and creating your own (e.g. monthOfYear, etc.).

**Comment by peter477** [comment]
Hello I‘m trying to program an Voiceassistant with an rhino file on my raspberry Pi 4 and I can‘t find an tutorial how to do that. Can sb help me ?

**Comment by dbartle** [comment]
> Hello I‘m trying to program an Voiceassistant with an rhino file on my raspberry Pi 4 and I can‘t find an tutorial how to do that. Can sb help me ?

This isn't related to the issue being discussed. GitHub issues are intended for bug reports and enhancement requests related to the software.

There are Raspberry Pi docs [here](https://picovoice.ai/docs/quick-start/rhino-raspberrypi-quick-start/). You can use a variety of the Rhino SDKs including Python and NodeJS. There are a lot of resources there to read, Console documentation for building a context, as well as the README files associated with each SDK.

**Comment by kenarsa** [comment]
I don't think we can include this in our immediate roadmap in the coming months, unfortunately. I am closing this right now but will re-open if priorities change on our end.
