### ISSUE TITLE
Rhino V2.1 and Rhino Context V3.0 libraries are not compatible

### ISSUE THREAD

**Issue by bmt1596** [Picovoice/rhino#706]
Hi Picovoice team, 
i am testing rhino on my board using Cortex A9 and got the following problem:

I used your library for arm11 to use for my Cortex A9 Chip because Cortex A9 is also based on arm11. I only successfully activated Rhino V2.1 version on my Board, for Rhino V3.0 library my program cannot start because it gives an Illegal instruction error.
Is there any way I can create Rhino Context for V2.1? Currently I can only create Rhino Context for V3.0 but it is not compatible with the current hardware and libraries on my Board.

Tks so much!!

**Comment by ksyeo1010** [comment]
We can't provide much help with errors/failures while using a device not officially supported. Creating an older version of Rhino 
 context is also unsupported. 

The official supported devices can be found on any Rhino docs page: https://picovoice.ai/docs/quick-start/rhino-c/.
