### ISSUE TITLE
How to bind Rust commands to Picovoice/Rhino so I can make a use that Rhino understands what I just said

### ISSUE THREAD

**Issue by Tschukedi** [Picovoice/rhino#711]
### What is the URL of the doc?

https://github.com/Picovoice/rhino/tree/master/binding/rust

### What is the nature of the issue?

Before I start, with this code I get a scope error:

``
fn main() {
    use rhino::RhinoBuilder;

    let rhino: Rhino = RhinoBuilder::RhinoBuilder::new(access_key, "../rhino/interaktionMitWindows_de.rhn")
        .sensitivity(0.42f32)
        .model_path("../rhino/rhino_params_de.pv")
        .init().expect("Unable to create Rhino");

}
``

I get the error : "error[E0412]: cannot find type `Rhino` in this scope"

**Comment by ErisMik** [comment]
You aren't importing the `Rhino` type. I recommend reading through the Rust reference book before opening issues like these: https://doc.rust-lang.org/reference/items/use-declarations.html
