### ISSUE TITLE
Support Czech langaue

### ISSUE THREAD

**Issue by skoky** [Picovoice/rhino#712]
Please support Czech language. I wish to use Picovoice / Rhino and Porcupine in my project, but I can't add Czech words. Thank you

**Comment by mrrostam** [comment]
I'm glad you're interested in using our products! I'll pass your request for Czech language support along to our language team. While adding new languages isn't currently on our immediate roadmap, we're always evaluating options for expansion; however, if you are an enterprise user or wish to engage with us on that level, please [contact sales](https://picovoice.ai/pricing/).

**Comment by skoky** [comment]
I did send email requesting enterprise access conditions. I have no reply so far. I think having supported more languages can more customer benefit from. Why should just my project pay for it?
