### ISSUE TITLE
Rhino should support ambiguous outputs 

### ISSUE THREAD

**Issue by ekcrisp** [Picovoice/rhino#721]
I am training a model in the console and for certain inputs I'm getting an error `Expression contains ambiguities with expression that results in different outputs with the same phrase.`

I understand the error, but do not understand why this is an issue. If any of the ambiguous outputs would work with my application logic Rhino should just pick one. Can the developers change this to a warning instead of an error, or allow a user to disable this check if they want to?

**Comment by ErisMik** [comment]
As an inference engine Rhino is typically used for well defined speaking applications. As such, the ambiguities that this error refers to are usually unintentionally created when writing out the context and therefore real errors. Being strict about the ambiguities also allows us to optimize with regards to model size, inference speed and inference accuracy.

Removing this check would introduce additional questions and variance. If it matches multiple, how would you pick which expression to match? What works for one use case might not for another. So keeping it deterministic makes it fair for all applications.

In the end they can usually be avoided by reworking your context to avoid them. Or for more complicated applications using a speech-to-text engine (such as either [Leopard](https://github.com/Picovoice/leopard) or [Cheetah](https://github.com/Picovoice/cheetah)) and parsing the output yourself. 

That being said this is the first request we've had for this specific feature, so if we get additional requests we may consider adding this as a feature in the future.
