### ISSUE TITLE
Rhino console frequently timing out

### ISSUE THREAD

**Issue by ekcrisp** [Picovoice/rhino#722]
I am building a model that is fairly complex. Whenever I save the validation times out and gives the error `Error updating element: Rhino could not validate context within the given timeout.` Is there a way to increase the timeout in the console? Or is there another way to get around this issue? I didn't see anything about this in the docs, thanks

**Comment by ErisMik** [comment]
Unfortunately the timeout is dictated by the backend system and cannot be changed. Usually the timeout occurs in contexts that chain / use many optional statements. 

I would suggest trying to reduce the number of `optional` statements overall, and reducing the amount of "chained" `optional`s in a single expression. You can do this by replacing the `optional`s with multiple expressions.

For example:

```
I (@macro1) (@macro2) rhino
```

In the extreme case can be split apart to:

```
I rhino
I @macro1 rhino
I @macro2 rhino
I @macro1 @macro2 rhino
```

but you may should success only going halfway, something like:

```
I (@macro2) rhino
I @macro1 (@macro2) rhino
```

**Comment by ekcrisp** [comment]
Making this change did improve performance, however in the example you give `(@macro1) (@macro2) rhino` is equivalent to listing each option separately. Why doesn't Rhino just do the same conversion? What is the point of using optionals if you have to list the options separately to improve performance? Thanks for the suggestion

**Comment by ekcrisp** [comment]
After further testing this didn't improve performance. I wrote a script to replace `start (@m_1) (@m_2) ... (@m_n) end` with permutations - empty, `@m_1`, `@m_2`, `@m_1 @m_2` ... `@m_1 ... m_n`  and this performed similarly to having optionals. I would expect this, since it's logically equivalent. Using fewer optionals improves performance a lot, but of course makes accepted model inputs more strict than I would like. If you have any other tips to improve performance I would appreciate it, thanks

**Comment by wycug2012** [comment]
how to initialize Picovoice Rhino by the Picovoice Porcupine wake word detection engine？

**Comment by ErisMik** [comment]
Hey @ekcrisp, unfortunately at this time I don't have any additional tips to improve performance.
