### ISSUE TITLE
Rhino: What counts as a user?

### ISSUE THREAD

**Issue by slickorange** [Picovoice/rhino#728]
### What is the URL of the doc?

https://picovoice.ai/pricing/

### What is the nature of the issue?

What exactly counts as a "user" when it comes to Rhino usage. If I use it in an Android app does it mean every app install?

**Comment by albho** [comment]
For Rhino, the definition of what a user is can change depending on what platform you are running on. For Android, every app install will count as a user once it is out of active development.
