### ISSUE TITLE
Rhino useful features idea

### ISSUE THREAD

**Issue by predond** [Picovoice/rhino#731]
I'm trying to configure a Rhino Speech-To-Intent context but many if not most words are said to has unknown pronunciation. With that on board I can't make model to handle switching lights. Can I bypass it in any way?

![obraz](https://github.com/user-attachments/assets/5135fa09-5780-4d25-9c2a-642369833f78)

The problem is that not only that words doesn’t work. Most of polish lamp type names have problems with pronunciation.
Also if I can ask for a little upgrade of Rhino web context creator. It would be very useful to enable custom words dictionary in Rhino, just like in speech-to-text dictionary, where I can set up any pronunciations on every word I can imagine. With that when I encounter a word that isn’t recognized by engine I could add my custom pronunciation to it and get my application work without concerning you with every word that is incaccessible.
The list of the most important specific words is following:
- główna lampa
- kinkiet
- kinkiety
- główną lampę
- jadalni
- salonu
- sypialni
- kuchni
- ledy
- tapety
- szafki
- lustra
- prysznica

As I noticed most of the words are available only in infinitives. Another good idea is to add microphone icon so I could record sample real voice data for the specific words.These are my ideas as an user.
I hope you will consider them.

**Comment by laves** [comment]
Thank you for your feedback, we'll pass it on to the team
