### ISSUE TITLE
Rhino Issue: PvRhino fails to upload dSYM to App Store Connect

### ISSUE THREAD

**Issue by r-token** [Picovoice/rhino#736]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Rhino docs
- [X] I have searched the existing issues for Rhino

### SDK

iOS

### Rhino package version

3.0

### Framework version

All Swift versions

### Platform

iOS

### OS/Browser version

iOS

### Describe the bug

After uploading my iOS app to App Store Connect, I get warnings that the archive's dSYM folder is missing DWARF files for two Picovoice frameworks:
- PvPorcupine.framework
- PvRhino.framework

### Steps To Reproduce

1. Build and archive an iOS app that uses Porcupine or Rhino (I'm using Xcode 16)
2. Upload the archive to App Store Connect
3. After the upload completes, you'll see the warnings that the archive did not include a dSYM for PvPorcupine.framework and PvRhino.framework

<img width="960" alt="pico-missing-dsyms" src="https://github.com/user-attachments/assets/a3ea6ec8-3866-4902-9c1a-631aab304aff">

### Expected Behavior

Those frameworks should include dSYMs that get included with the archive when uploaded to App Store Connect.

**Comment by laves** [comment]
we'll track this one over on https://github.com/Picovoice/porcupine/issues/1311
