### ISSUE TITLE
Clarification on Sharing Rhino Context YAML Files for Non-Commercial Use

### ISSUE THREAD

**Issue by ronspeclin** [Picovoice/rhino#742]
Hello,

Quick question:

I am creating simple Rhino contexts in the Picovoice Console and would like to share these YAML configuration files with others as templates or for educational purposes (without sharing the compiled .rhn files).

Does sharing the YAML context file (which only includes the structure of intents, slots, and logic) violate your Terms of Use?

**Comment by matt200-ok** [comment]
Hello @ronspeclin,

The sharing of Rhino context configuration files for Non-Commercial purposes does not violate the Picovoice Terms of Use.
