### ISSUE TITLE
Rhino Issue: Plugin version mismatch

### ISSUE THREAD

**Issue by darys58** [Picovoice/rhino#747]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Rhino docs
- [X] I have searched the existing issues for Rhino

### SDK

Flutter

### Rhino package version

3.0.3

### Framework version

Flutter 3.19.6

### Platform

iOS

### OS/Browser version

macOS 14.6.1

### Describe the bug

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "ios-voice-processor":
  In Podfile:
    flutter_voice_processor (from `.symlinks/plugins/flutter_voice_processor/ios`) was resolved to 1.1.2, which depends on
      ios-voice-processor (~> 1.2.0)

    rhino_flutter (from `.symlinks/plugins/rhino_flutter/ios`) was resolved to 3.0.3, which depends on
      Rhino-iOS (~> 3.0.1) was resolved to 3.0.1, which depends on
        ios-voice-processor (~> 1.1.0)

### Steps To Reproduce

Starting the app with picovioce_flutter: 3.0.3

### Expected Behavior

Is there a version of Rhino-iOS that works with ios-voice-processor (~> 1.2.0)?

**Comment by albho** [comment]
@darys58 Apologies for the delayed response -  an update to Rhino is in progress that will fix this issue, I'll update this thread once it's out.
