### ISSUE TITLE
Commercial usage of free access key.

### ISSUE THREAD

**Issue by NeoZ882** [Picovoice/rhino#749]
Hello. I am Neo. I notice that the rhino project is based on Apache License Version 2.0. Thus, I have 2 questions: 
1. Will the free access key of rhino change in future?
2. Is the free access key of rhino available in commercial usage?

I would be very appreciated if you could help me with the above questions.

**Comment by albho** [comment]
1. There are currently no plans to eliminate the free tier, although this cannot be guaranteed for the future.
2. Yes, as long as you are within your plan limits and compliant with the Picovoice [Terms of Use](https://picovoice.ai/docs/terms-of-use/). For more details, please refer to our [pricing page](https://picovoice.ai/pricing/).
