### ISSUE TITLE
Rhino Issue: how to solve the bitcode issue in ios

### ISSUE THREAD

**Issue by markchiuleo** [Picovoice/rhino#751]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Rhino docs
- [X] I have searched the existing issues for Rhino

### SDK

Flutter

### Rhino package version

3.0.3

### Framework version

flutter 3.22.2

### Platform

iOS

### OS/Browser version

ios 18

### Describe the bug

Please correct the following issues and upload a new binary to App Store Connect.

ITMS-90668: Invalid Bundle Executable - The executable file 'Runner.app/Frameworks/PvRhino.framework/PvRhino' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu.

### Steps To Reproduce

xcode cloud build
get 
Invalid Bundle Executable. The executable file 'Runner.app/Frameworks/PvRhino.framework/PvRhino' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu.
<img width="1340" alt="截圖 2024-11-28 下午4 57 26" src="https://github.com/user-attachments/assets/f22759ce-0450-4f00-b644-a61be1df1e68">

### Expected Behavior

how do i solve this error?
App Store Connect say I need solve it than can upload app.

**Comment by albho** [comment]
Hey @markchiuleo, please give the latest [rhino_flutter](https://pub.dev/packages/rhino_flutter) package a try - it should fix the issue.
