### ISSUE TITLE
Libraries for armhf and arm64

### ISSUE THREAD

**Issue by reinzor** [Picovoice/rhino#83]
Hi,

I am working on a [ROS wrapper](https://github.com/reinzor/picovoice_ros) for `porcupine` and `rhino`. The ROS build farm is building for linux for architectures `armhf`, `arm64` and `amd64`. For now I am only using the [this library](https://github.com/Picovoice/rhino/blob/master/lib/linux/x86_64/libpv_rhino.so) which causes the [`arm64`](https://build.ros.org/job/Nbin_ufv8_uFv8__picovoice_driver__ubuntu_focal_arm64__binary/) and [`armhf`](https://build.ros.org/job/Nbin_ufhf_uFhf__picovoice_driver__ubuntu_focal_armhf__binary/) builds to fail. What libraries should I use for the `armhf` and `arm64` linux builds? Or aren't these available?

Thanks!

**Comment by reinzor** [comment]
For reference https://github.com/ros/rosdistro/pull/28904

**Comment by kenarsa** [comment]
I'm not sure what does builds are for. but my guess is that you should be able to use one of the raspberry pi builds https://github.com/Picovoice/rhino/tree/master/lib/raspberry-pi/cortex-a53-aarch64

might make sense to involve someone who created the build system there in this issue

**Comment by reinzor** [comment]
Thanks, will go with that!
