### ISSUE TITLE
Rhino Issue: React-native fatal errors when no slot defined

### ISSUE THREAD

**Issue by Vincz** [Picovoice/rhino#88]
This line breaks when there is no slots defined (as range `0...-1` is not suported).

https://github.com/Picovoice/rhino/blob/5e5feebbe08d466a6475623c3a611d5cc4b3ce73/binding/react-native/ios/Rhino.swift#L102

It results with a `Fatal error: Can't form Range with upperBound < lowerBound`.
Just need to wrap the slots processing with a `numSlots > 1`.

**Comment by kenarsa** [comment]
Thank you. We will look into this ASAP.

**Comment by laves** [comment]
@Vincz, this should be fixed now. Update the rhino-react-native npm package and it should work with no slots defined. Thanks for reporting!
