### ISSUE TITLE
Train more Expressions 

### ISSUE THREAD

**Issue by TruongLCC** [Picovoice/rhino#90]
How I can train so many Expressions in a intent. In the docs , it just trains one Expression by pressing mic button and talking, but when having more Expressions, how should I say ?

**Comment by dbartle** [comment]
Speaking to the microphone _does not do any training_. The models are entirely built through transfer learning and based on the text typed into Picovoice Console. The docs are showing you how to test your model, and automatically trains it for you when you use the microphone button, if it detects changes.

If you want more expressions, just type them in like so: https://picovoice.ai/docs/quick-start/console-rhino/#adding-expressions-to-an-intent
